export type Product<T extends Record<string, any> = Record<string, any>> = {
  name: string;
  price: string;
  url: string;
  brand?: string;
  description?: string;
  originalPrice?: string;
  discount?: string;
  currency?: string;
  stock?: string;
  availability?: string;
  rating?: string;
  reviewCount?: number;
  category?: string;
  subCategory?: string;
  tags?: string[];
  images?: string[];
  specs?: Record<string, string>;
  priceNumeric?: number;
  slug?: string;
  metadata?: Record<string, any>;
} & T;

export type RawProductInput<T extends Record<string, any> = Record<string, any>> = {
  name?: string;
  title?: string;
  productName?: string;
  price?: string | number;
  priceNumeric?: number;
  url?: string;
  image?: string;
  thumbnail?: string;
  images?: string[];
  slug?: string;
  id?: string;
  productId?: string;
  brand?: string;
  description?: string;
  originalPrice?: string;
  discount?: string;
  currency?: string;
  stock?: string;
  availability?: string;
  rating?: string;
  reviewCount?: number;
  category?: string;
  subCategory?: string;
  tags?: string[];
  specs?: Record<string, string>;
  metadata?: Record<string, any>;
} & T;

export interface CartItem {
  id: string;
  cart_id: string;
  external_id?: string;
  product_url: string;
  name: string;
  price: string;
  price_numeric: number;
  currency: string;
  image: string;
  brand: string;
  category: string;
  quantity: number;
}

export interface CartPayload {
  cart_id: string;
  shopper_id: string;
  site_id: string;
  status: string;
  items: CartItem[];
  total: number;
  currency: string;
  item_count: number;
}

export type DisplayConfig = Record<string, string>;

export interface AkropolysConfig {
  siteId?: string;
  apiUrl?: string;
  apiToken?: string;
  shopperId?: string;
  vertical?: 'commerce' | 'property' | 'motor' | 'blog' | string;
  onCheckout?: (cart: CartPayload) => void;
  onError?: (error: AkropolysError) => void;
  authLoading?: boolean;
  indexContent?: boolean;
  display?: DisplayConfig;
}

export interface SearchRequest {
  query: string;
  siteId: string;
  limit?: number;
}

export interface SearchResult {
  id: string;
  score: number;
  product: Product;
}

export interface SearchResponse {
  results: SearchResult[];
  query: string;
}

export interface IngestResponse {
  success: boolean;
  message?: string;
  count?: number;
}

export interface AkropolysError {
  status: number;
  message: string;
}

export interface AkropolysTheme {
  primaryColor?: string;
  backgroundColor?: string;
  textColor?: string;
  fontFamily?: string;
  borderRadius?: string;
}

export interface CheckoutConfig {
  payment_methods: Record<string, { enabled: boolean }>;
}

export interface PaymentInitResponse {
  merchantReference: string;
  checkoutRequestId?: string;
}

export interface PaymentStatusResponse {
  status: 'PENDING' | 'COMPLETED' | 'FAILED';
  message?: string;
}

export type ChatAction =
  | { type: 'add_to_cart'; [key: string]: any }
  | { type: 'remove_from_cart'; [key: string]: any }
  | { type: 'clear_cart'; [key: string]: any }
  | { type: 'view_cart'; [key: string]: any }
  | { type: 'checkout'; [key: string]: any }
  | { type: 'request_phone'; [key: string]: any }
  | { type: 'awaiting_payment'; merchantReference?: string | null; [key: string]: any }
  | { type: string; [key: string]: any };

export interface ChatAttachment {
  type: 'image';
  /** base64 data URL, e.g. "data:image/jpeg;base64,..." */
  data: string;
}

export interface ContentIngestPayload {
  url: string;
  title: string;
  text: string;
  capturedAt: number;
}

/**
 * Style attributes extracted from a product or user-uploaded image.
 * Used for complementary-product matching ("find a dress to match my shoes").
 */
export interface StyleDNA {
  dominant_colors: string[];
  color_palette: string;
  aesthetic: string[];
  texture: string;
  formality: string;
  season: string;
  style_tags: string[];
  /** Natural-language query generated by Gemini for vector search */
  match_query: string;
}

/** Response from POST /search/visual — extends SearchResponse with style context */
export interface VisualSearchResponse extends SearchResponse {
  style_dna?: StyleDNA;
  match_query?: string;
}


