// Concatenates modular CSS files from src/styles/ and emits minified TS string for shadow root.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';

function minifyCss(css) {
  return css
    // 1. Remove comments
    .replace(/\/\*[\s\S]*?\*\//g, '')
    // 2. Collapse all multi-whitespace/newlines into single space
    .replace(/\s+/g, ' ')
    // 3. Remove space around symbols: { } ; : , > + ~
    .replace(/\s*([{};:,>+~])\s*/g, '$1')
    // 4. Remove space in !important
    .replace(/!\s+important/g, '!important')
    // 5. Zero unit stripping: 0px, 0rem, 0em, 0% -> 0
    .replace(/(?<=[:\s,(])0(?:px|rem|em|%|pt)/g, '0')
    // 6. Leading zero stripping: 0.5s -> .5s
    .replace(/(?<=[:\s,(])0\.(\d+)/g, '.$1')
    // 7. Remove unnecessary trailing semicolons
    .replace(/;}/g, '}')
    .trim();
}

const MODULES = [
  'base.css',
  'chat.css',
  'search.css',
  'scripts.css',
  'voice.css',
  'themes.css',
  'animations.css',
];

let rawCss = '';
const stylesDir = 'src/styles';

if (existsSync(join(stylesDir, 'base.css'))) {
  rawCss = MODULES.map(m => readFileSync(join(stylesDir, m), 'utf8')).join('\n');
  writeFileSync('src/styles.css', rawCss, 'utf8');
} else {
  rawCss = readFileSync('src/styles.css', 'utf8');
}

const minifiedCss = minifyCss(rawCss);

const out = 'src/generated/cssText.ts';
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `// AUTO-GENERATED by scripts/gen-css.mjs — do not edit.\nexport default ${JSON.stringify(minifiedCss)};\n`);
console.log(`generated ${out} (${minifiedCss.length} bytes, saved ${(rawCss.length - minifiedCss.length)} bytes / ${((rawCss.length - minifiedCss.length)/1024).toFixed(1)} KB)`);



