export type DisplayConfig = Record<string, string>;

export interface Entity {
  url: string;
  fields: Record<string, any>;
}

export type Product = Entity;

export type RawProductInput = {
  url?: string;
  [key: string]: any;
};

export interface CartItem {
  id: string;
  cart_id: string;
  external_id?: string;
  product_url: string;
  name: string;
  price: string;
  price_numeric: number;
  currency: string;
  image: string;
  brand: string;
  category: string;
  quantity: number;
}

export interface CartPayload {
  cart_id: string;
  shopper_id: string;
  site_id: string;
  status: string;
  items: CartItem[];
  total: number;
  currency: string;
  item_count: number;
}

export interface AkropolysConfig {
  siteId?: string;
  apiUrl?: string;
  apiToken?: string;
  shopperId?: string;
  vertical?: 'commerce' | 'property' | 'motor' | 'blog' | string;
  onCheckout?: (cart: CartPayload) => void;
  onError?: (error: AkropolysError) => void;
  authLoading?: boolean;
  display?: DisplayConfig;
}

export interface SearchRequest {
  query: string;
  siteId: string;
  limit?: number;
}

export interface SearchResult {
  id: string;
  score: number;
  product: Product;
}

export interface SearchResponse {
  results: SearchResult[];
  query: string;
}

export interface IngestResponse {
  success: boolean;
  message?: string;
  count?: number;
}

export interface AkropolysError {
  status: number;
  message: string;
}

export interface AkropolysTheme {
  primaryColor?: string;
  backgroundColor?: string;
  textColor?: string;
  fontFamily?: string;
  borderRadius?: string;
}

/**
 * Style attributes extracted from a product or user-uploaded image.
 * Used for complementary-product matching ("find a dress to match my shoes").
 */
export interface StyleDNA {
  dominant_colors: string[];
  color_palette: string;
  aesthetic: string[];
  texture: string;
  formality: string;
  season: string;
  style_tags: string[];
  /** Natural-language query generated by Gemini for vector search */
  match_query: string;
}

/** Response from POST /search/visual — extends SearchResponse with style context */
export interface VisualSearchResponse extends SearchResponse {
  style_dna?: StyleDNA;
  match_query?: string;
}


